### ISSUE TITLE
Continue comms for recruiting contributors

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/curriculum-localization#3]
Currently we have done the following for communication about our November Campaign:
- [Newsletter](https://medium.com/@MozLearn/november-2016-community-newsletter-youth-leadership-9e01e137cbe8#.hvka701kq)
- [Blog Post](https://learning.mozilla.org/blog/help-us-teach-the-web-in-your-language)

We need to continue this via other media to recruit more contributors.

@jvallera and @amirad would you be able to suggest some other communication media (the Learning newsletter for e.g.) that we can use to get the word out about this campaign better? I can come up with copy for your recommendations and would you be able to approve it as well?

**Comment by jvallera** [comment]
Hi @gideonthomas. Is the hope to recruit more people beyond the list of folks we put together a few months back? Happy to suggest more communication channels but direct outreach to individuals (involved with Clubs) is usually the best way to get people to localize content. Are we still trying start small and grow as needed?

**Comment by gideonthomas** [comment]
@jvallera I don't think we have reached out to those people directly. Should we? 

Yeah I think we want to try starting small but at the same time getting good locale coverage.

**Comment by jvallera** [comment]
Oh, I thought that happened when the survey went out to see how they would like to contribute? I think following up with each of them is the best way to get contributions.

**Comment by gideonthomas** [comment]
Ok perfect, thanks @jvallera!

**Comment by hannahkane** [comment]
@gideonthomas / @jvallera - Did you two sync up about who would do the reaching out? How can I help?

**Comment by jvallera** [comment]
@hannahkane we connected about the email outreach to contributors, but I haven't seen the list yet. @gideonthomas are there any Arabic translators on the list? We have a high priority need for Arabic content with one of our partners. If we can find volunteers to do it would the process be the same for them?

**Comment by gideonthomas** [comment]
@jvallera I don't believe we have any Arabic translators. I'm a bit hesitant to include them in this campaign because of the implications of right-to-left translations on the web. At present, I don't think our web curriculum pages are right-to-left friendly so it would be nice to figure out what we need to do to make that possible (we actually need to do this at a much higher level for all our localized websites as well). Let me know if you think otherwise though.

@hannahkane would you be able to send me the list of emails we used for the survey? I would like to contact them directly.

**Comment by jvallera** [comment]
Hmm. I understand @gideonthomas. What if people can translate the content into Arabic using a text doc and we share it in PDF form for now? Is that something we could use in the future? and if I recruited people could we add them to the incentives process? 

Just trying to brainstorm because one of our partners is in Jordan and can not start clubs in the areas they need to without Arabic.

**Comment by gideonthomas** [comment]
@jvallera that's an interesting idea. I think if they stick to the Google Docs version of the activities that actually might work. Let me know what you think.
Absolutely, they will be part of the incentive process.

**Comment by jvallera** [comment]
Ok, thanks @gideonthomas I will see if I can find some people who can help and keep you posted.

**Comment by hannahkane** [comment]
@gideonthomas - I think we should write to the people who took the survey and gave us their email addresses for further contact (as opposed to everyone we sent the survey link to). You can access that, right?

**Comment by gideonthomas** [comment]
Ah yeah that makes sense! Yep, I'll take a look and send the email out, thanks @hannahkane

**Comment by jvallera** [comment]
@gideonthomas where is the best place to add names and emails - a few Arabic translators have offered to help.

**Comment by gideonthomas** [comment]
Hi @jvallera would you be able to (or ask them to) fill out this form: https://goo.gl/forms/FU7BMpK7yXLANayF3

We're keeping track of the contributors there so it would be nice to have that be the one place to get that information from.

Also, for instructions on how to begin the process, directing them to the website: https://mozilla.github.io/curriculum-localization/ and/or getting them in touch with @hannahkane or me would be a good start.

**Comment by jvallera** [comment]
Hi @gideonthomas ok if I have them fill the form out when they finish the translation? - it will be in doc/pdf form but will let you know. So far there three Arabic translators working on the offline activities curriculum.

**Comment by gideonthomas** [comment]
@jvallera sounds great! Thank you very much

**Comment by jvallera** [comment]
[A Strong Wind Blows for Web Literacy.docx](https://github.com/mozilla/curriculum-localization/files/594808/A.Strong.Wind.Blows.for.Web.Literacy.docx)

This is the Arabic translation of A strong Wind Blows for Web Literacy. Does it work in this format? I like that the English version is included so we and other readers can see both. Thoughts on how this could be linked or made available through the site?

I think once we have a few collected we should go through an evaluation process to make sure they are correctly translated. A that point we can merge them into one folder or file and open evaluation up to all who translated. 

Also, a translate of web mechanics speed dating should of come through the form.

**Comment by gideonthomas** [comment]
@jvallera, a few questions:
- Are they aware that the format that they are presenting to us (i.e. the link above) is exactly what we will be putting up on the site? We won't be converting them into Thimble/Github/Google Docs. So when we put it on the learning site, anyone who wants to view that translation will need to download that file to their computer and use MS Word or something like that to look at it. If that is the intended workflow, this should be fine.
- Where are they getting the source content from? It looks like they might be getting it from the learning site directly. Can they use the activities from https://mozilla.github.io/curriculum-localization/curriculum/ instead? This has a bunch of bug fixes.
- It would be good to ask them how they will be localizing images for e.g. If they are not going to be localizing those, it will inform our tooling decisions for RTL (we might need to use Pontoon or something).
- How do you envision the vetting process going about? Would we just circulate the localized curriculum between them to peer-review?

**Comment by jvallera** [comment]
Hi @gideonthomas do you mind jumping on a call? easier than typing for me.

**Comment by gideonthomas** [comment]
@jvallera sure! i'll book something on your cal

**Comment by gideonthomas** [comment]
Keeping this open to record comms feedback
