### ISSUE TITLE
List of languages taken up

### ISSUE THREAD

**Issue by SubhrajyotiSen** [mozilla/curriculum-localization#5]
Is there a way for participants to know which languages have already been taken up (according to the files) so that multiple people don't work on same files in the same language?

**Comment by gideonthomas** [comment]
Hi @SubhrajyotiSen, unfortunately, we don't currently have an automated way of doing that. For this campaign, we anticipated that connecting those who have an interest in localizing in the same language would suffice but I guess we did not account for the case when someone is interested in localizing in multiple languages (good feedback for our next campaign).

As a quick fix, I can connect you with folks who might already be localizing in a language that you are interested in. Do you have a preference of which other languages you may be interested in?

**Comment by SubhrajyotiSen** [comment]
Can we use GitHub issues as a means of keeping track of who has taken up which languages?
I mean after a person fills up the initial form , it can be used to update an issue in a similar to the one used in the MozFest proposals this year
